[book]
authors = ["jingdor"]
language = "en"
multilingual = false
src = "src"

[output.html]
additional-css = ["style.css"]
additional-js = ["sidebar.js"]

[preprocessor.d2]
layout = "dagre"
inline = true
output-dir = "d2"